### ISSUE TITLE
Please enhance the documentation. 

### ISSUE THREAD

**Issue by j-j-kam** [sweekarsud/Goodness-of-Pronunciation#10]
Good day. Your code seems to be very good and promising, but the documentation for it is quite confusing, unfortunately. Here are some issues I face. 

I have followed these instructions so far: 

1. I have placed the folder where you've said. 
2. I have found a trained model and placed it here:
/Users/myname/Desktop/kaldi-master/egs/native_acoustic_model/kaldi-generic-en-tdnn_f-r20190609.tar.xz

I do not understand where should I place my wav file and feed it to the program. Let's say that I already have the code that does three things: forced alignment with a given text and a wav. file; free recognition; outputs the said words in a file. All I need to do is get the GOP algorithm but I fail to understand how to do it with your code. 

I think if the documentation would be more detailed users like me would save a lot of their time and give more credit to you. 

<img width="260" alt="img" src="https://user-images.githubusercontent.com/70814983/124796476-7e586780-df51-11eb-8672-99ebde9623b0.png">

**Comment by sweekarsud** [comment]
As mentioned in the document, both posterior_infile.ark and alignment_infile.txt need to be passed as inputs to the GoP computation code (prop_gop_eqn.py). 

To generate these files you need a pre-trained model and a .wav file for which the GoP score is to be computed. However, we do not provide the pre-trained model and should be trained by yourself. The procedure to generate the posterior probability (posterior_infile.ark) and forced alignment (alignment_infile.txt) can be referred to in our paper and is a generic procedure that can be found elsewhere. Our code does not need any .wav file and only needs these two processed files that are to be followed by yourself.

**Comment by amandeepbaberwal** [comment]
Hi did you make it work? I found it very confusing and would love to know how where to start. Thanks
