### ISSUE TITLE
how to obtain reqd_files

### ISSUE THREAD

**Issue by nipengmath** [sweekarsud/Goodness-of-Pronunciation#2]
Hi @sweekarsud thanks for your greatful work。
When I prepare the alignment.txt and posterior.txt file, I got some errors, So can you give an example which input is a wav file and output is gop score.
thank you very much!

**Comment by sweekarsud** [comment]
Hi @nipengmath.
Could you please tell me how you created the alignment.txt and posterior.txt.
In general, the posteriors are extracted for the input wav file (you'll require a trained acoustic model for this) and the phoneme alignments are created using the forced alignment. When you have both of these then you can compute the GoP score using the provided python file.
