### ISSUE TITLE
Got wired result

### ISSUE THREAD

**Issue by zhushaojin** [sweekarsud/Goodness-of-Pronunciation#3]
Hi, I just ran the code as described.

I used trained nnet3 model as input.
First, use /nnet3bin/nnet3-compute --apply-exp=true to get the posterior matrix,
Then, use steps/nnet3/align.sh to get the align result.
Finally, use the prop_gop_eqn.py to get gop score.

I have several question:
1. Are the steps above correct? I used --apply-exp=true since prop_gop_eqn.py didn't accept negative number
2. the gop score I got in the end is very small, sometimes even negative. How can I map them into 100 score scale?
follow is an example of result:
> SIL   8.342001
> P_B   0.136489
> EH1_I   0.128400
> N_I   -0.630409
> S_I   -0.693370
> AH0_I   -0.413519
> L_E   -0.636497
> SIL   8.333837
> P_B   -0.003946
> EH1_I   0.182815
> N_I   -0.727751
> S_I   -0.544970
> AH0_I   0.782079
> L_E   -0.184871
> P_B   -0.051290
> EH1_I   0.022745
> N_I   -0.276879
> S_I   -0.096772
> AH0_I   0.767991
> L_E   0.951546
> SIL   9.210120

Thank you very much

**Comment by sweekarsud** [comment]
Hi @zhushaojin 
1) The steps you have used to compute the posterior probability matrix and the alignments are correct.
2) There is nothing wrong in getting negative values (GoP scores), some methods tend to use modulus for that reason, which we haven't. To get the GoP scores in a particular range, you will need to do some kind of normalization on these scores.

**Comment by saireddy12** [comment]
can you please clearly explain how to generate the input files 
 and what are required files for input data creation

**Comment by saireddy12** [comment]
> steps

from where did you get the trained nnet3 model and where did you place the model if the model was pretrained can you please provide me the link
can you please give me the detailed explanation of getting required files
