### ISSUE TITLE
steps to use but got out of range issue

### ISSUE THREAD

**Issue by ahmedalbahnasawy** [sweekarsud/Goodness-of-Pronunciation#5]
Thank you for your interesting paper and your great repository. I’m able to run the default example in reqd_file. I’m trying to share my script with my trained model for using them for another input. I trained nnet3 acoustic model on Librispeech dataset. I used nnet3-compute to extract the posterior matrix and pass them to modify_post.sh
```
 nnet3-compute  --apply-exp=true --use-gpu=no --online-ivectors=scp:../../librispeech/s5/exp/nnet3_cleaned/ivectors_test_other_hires/ivector_online.scp --online-ivector-period=10 --frames-per-chunk=50 --extra-left-context=0 --extra-right-context=0 --extra-left-context-initial=-1 --extra-right-context-final=-1 ../../librispeech/s5/exp/nnet3_cleaned/tdnn_1d_sp/final.mdl 'ark,s,cs:apply-cmvn --norm-means=false --norm-vars=false --utt2spk=ark:data/test_10short/split25/1/utt2spk scp:data/test_10short/split25/1/cmvn.scp scp:data/test_10short/split25/1/feats.scp ark:- |' 'ark:| copy-feats --compress=false ark:- ark,scp:exp/probs_test_10short/output.9.ark,exp/probs_test_10short/output.9.scp'
```
Then I used align.sh to generate the phoneme alignment and save them in txt format using show-alignments command :
```
show-alignments ../../../../librispeech/s5/data/lang/phones.txt ../../../../librispeech/s5/exp/nnet3_cleaned/tdnn_1d_sp/final.mdl "ark:gunzip -c ali.1.gz |" | head > alignment_infile.txt
```
I generated Lookup_table.txt from show_transitions.txt as show-transitions command do 

When I run python prop_gop_eqn.py posterior_infile.ark alignment_infile.txt
[alignment_infile.txt](https://github.com/sweekarsud/Goodness-of-Pronunciation/files/4948221/alignment_infile.txt)
 I got an Error list index out of range at line 64 

```
tmp_post = float(posterior[cum_number_of_segments[x]+y][tmp_pdf])
```
Are the steps above correct ?

**Comment by ahmedalbahnasawy** [comment]
@sweekarsud any comments to this issue

**Comment by sweekarsud** [comment]
Hello, your approach is correct. Verify whether the number of rows in the posterior.txt which correspond to number of frames in the speech sample is equivalent to number of frames or values denoted in alignments.txt file.

**Comment by sweekarsud** [comment]
I have closed this issue for now, kindly reopen if you face any further problems.
