### ISSUE TITLE
What should I do if I want to detect a new piece of audio‘gop？

### ISSUE THREAD

**Issue by red-fly** [sweekarsud/Goodness-of-Pronunciation#8]
What should I do if I want to detect a new piece of audio‘gop？

**Comment by sweekarsud** [comment]
To generate the GoP score on a new audio file, you would first need to generate the alignment_infile.txt which is nothing but the phoneme alignment for the audio file and the posterior_infile.ark which is the posterior probability of the audio file. To generate these two models you would need to train your own ASR model.
